[package]
name    = "toshi"
version = "0.1.0"
authors = ["Stephen Carman <shcarman@gmail.com>"]

[[bin]]
name = "start-toshi"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
gotham            = "0.2.1"
gotham_derive     = "0.2.1"
hyper             = "0.11"
mime              = "0.3.7"
serde             = "1.0.66"
serde_derive      = "1.0.66"
serde_json        = "1.0.20"
lazy_static       = "1.0.1"
futures           = "0.1.17"
tantivy           = "0.6.0"
config            = "0.8.0"
log               = "0.4.2"
pretty_env_logger = "0.2.3"

[profile.release]
lto = true